name: CI/CD Pipeline

on:
  push:
    paths:
      - 'src/**'
      - 'checkstyle.xml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - 'checkstyle.xml'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build, Test, Checkstyle, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # 3. Кэшируем Maven репозиторий
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-v2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-v2-

      # 4. Сборка, тесты и Checkstyle через один шаг Maven Verify
      - name: Build, Test & Checkstyle
        run: chmod +x ./mvnw && ./mvnw verify

      # 5. Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Build и Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nbank-tests:${{ github.sha }}
